In [1]:
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import requests

In [94]:
player_stats = pd.read_csv('../data/player_stats.csv')

In [344]:
player_stats.Tournament.value_counts()

2014 USAU Club Championships    344
2015 USAU Club Championships    327
2013 USAU Club Championships    321
2014 WUCC                        48
2012 WUGC                        28
2013 World Games                  6
Name: Tournament, dtype: int64

In [220]:
fury = []
riot = []

for item in player_stats.Team:
    if item == 'FURY':
        fury.append(1)
        riot.append(0)
    elif item == 'RIOT':
        riot.append(1)
        fury.append(0)
    else:
        fury.append(0)
        riot.append(0)

In [221]:
player_stats['fury'] = fury
player_stats['riot'] = riot

In [349]:
year = []

for item in player_stats.Tournament:
    if '2012' in item:
        year.append(2012)
    elif '2013' in item:
        year.append(2013)
    elif '2014' in item:
        year.append(2014)
    elif '2015' in item:
        year.append(2015)

In [351]:
player_stats['year'] = year

In [354]:
player_stats[player_stats.wg13 ==1].head()

,Unnamed: 0,Team,Number,Name,Goal,GPG,Assist,APG,Block,BPG,...,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot,year
0,0,FURY,4,ALEX SNYDER,3,0.250000,32,2.666667,NaN,NaN,...,2012 WUGC,2,12.00,1,1,1,0,1,0,2012
1,1,FURY,19,GEORGIA BOSSCHER,13,1.083333,14,1.166667,NaN,NaN,...,2012 WUGC,2,12.00,1,1,1,0,1,0,2012
3,3,FURY,13,CREE HOWARD,15,1.250000,6,0.500000,NaN,NaN,...,2012 WUGC,2,12.00,1,1,0,0,1,0,2012
15,15,FURY,33,ANNA NAZAROV,4,0.333333,8,0.666667,NaN,NaN,...,2012 WUGC,2,12.00,1,1,1,0,1,0,2012
80,107,FURY,4,ALEX SNYDER,2,0.285714,11,1.571429,7,1,...,2013 USAU Club Championships,2,4.14,1,1,1,0,1,0,2013

In [294]:
player_stats[player_stats.wg13 ==1].describe()

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot
count,104.000000,80.000000,104.000000,104.000000,104.000000,104.000000,27.000000,27.000000,27.000000,27.000000,104.000000,104.000000,80.000000,104.000000,104.000000,104.000000,104.000000,104,104
mean,736.711538,22.325000,2.836538,0.564332,2.817308,0.561126,2.222222,0.317460,4.592593,0.656085,5.365385,2.278846,10.825375,0.076923,0.423077,0.182692,1.615385,0,1
std,370.574277,23.614936,3.177929,0.659820,3.314471,0.619499,2.606697,0.372385,4.190275,0.598611,2.437800,0.817963,4.594003,0.267760,0.496440,0.388285,0.792044,0,0
min,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,4.430000,0.000000,0.000000,0.000000,0.000000,0,1
25%,326.750000,7.000000,0.750000,0.107143,0.000000,0.000000,0.000000,0.000000,1.000000,0.142857,6.000000,2.000000,4.430000,0.000000,0.000000,0.000000,2.000000,0,1
50%,521.500000,14.500000,2.000000,0.309524,2.000000,0.333333,2.000000,0.285714,4.000000,0.571429,7.000000,3.000000,14.000000,0.000000,0.000000,0.000000,2.000000,0,1
75%,1254.250000,24.250000,4.000000,0.839286,4.000000,0.857143,4.000000,0.571429,6.500000,0.928571,7.000000,3.000000,14.170000,0.000000,1.000000,0.000000,2.000000,0,1
max,1280.000000,91.000000,15.000000,3.000000,17.000000,2.428571,9.000000,1.285714,16.000000,2.285714,7.000000,3.000000,14.170000,1.000000,1.000000,1.000000,2.000000,0,1

In [295]:
player_stats[player_stats.fury ==1].describe()

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot
count,129.000000,105.000000,129.000000,129.000000,129.000000,129.000000,25.000000,25.000000,25.000000,25.000000,129.000000,129.000000,105.000000,129.000000,129.000000,129.000000,129.000000,129,129
mean,505.240310,24.990476,3.666667,0.550388,3.612403,0.543282,2.600000,0.371429,4.760000,0.680000,6.767442,2.201550,10.878857,0.124031,0.503876,0.201550,1.488372,1,0
std,401.070828,20.216851,3.534060,0.602352,4.330686,0.561519,2.345208,0.335030,2.758019,0.394003,3.516727,0.402722,3.838365,0.330902,0.501934,0.402722,0.876038,0,0
min,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,4.140000,0.000000,0.000000,0.000000,0.000000,1,0
25%,110.000000,10.000000,1.000000,0.142857,1.000000,0.142857,1.000000,0.142857,3.000000,0.428571,6.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,1,0
50%,560.000000,19.000000,3.000000,0.428571,2.000000,0.416667,2.000000,0.285714,5.000000,0.714286,7.000000,2.000000,12.000000,0.000000,1.000000,0.000000,2.000000,1,0
75%,872.000000,33.000000,5.000000,0.714286,5.000000,0.857143,4.000000,0.571429,6.000000,0.857143,7.000000,2.000000,13.430000,0.000000,1.000000,0.000000,2.000000,1,0
max,1033.000000,77.000000,16.000000,4.000000,32.000000,3.000000,7.000000,1.000000,12.000000,1.714286,12.000000,3.000000,13.600000,1.000000,1.000000,1.000000,2.000000,1,0

In [296]:
player_stats[player_stats.riot ==1].describe()

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot
count,104.000000,80.000000,104.000000,104.000000,104.000000,104.000000,27.000000,27.000000,27.000000,27.000000,104.000000,104.000000,80.000000,104.000000,104.000000,104.000000,104.000000,104,104
mean,736.711538,22.325000,2.836538,0.564332,2.817308,0.561126,2.222222,0.317460,4.592593,0.656085,5.365385,2.278846,10.825375,0.076923,0.423077,0.182692,1.615385,0,1
std,370.574277,23.614936,3.177929,0.659820,3.314471,0.619499,2.606697,0.372385,4.190275,0.598611,2.437800,0.817963,4.594003,0.267760,0.496440,0.388285,0.792044,0,0
min,301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,4.430000,0.000000,0.000000,0.000000,0.000000,0,1
25%,326.750000,7.000000,0.750000,0.107143,0.000000,0.000000,0.000000,0.000000,1.000000,0.142857,6.000000,2.000000,4.430000,0.000000,0.000000,0.000000,2.000000,0,1
50%,521.500000,14.500000,2.000000,0.309524,2.000000,0.333333,2.000000,0.285714,4.000000,0.571429,7.000000,3.000000,14.000000,0.000000,0.000000,0.000000,2.000000,0,1
75%,1254.250000,24.250000,4.000000,0.839286,4.000000,0.857143,4.000000,0.571429,6.500000,0.928571,7.000000,3.000000,14.170000,0.000000,1.000000,0.000000,2.000000,0,1
max,1280.000000,91.000000,15.000000,3.000000,17.000000,2.428571,9.000000,1.285714,16.000000,2.285714,7.000000,3.000000,14.170000,1.000000,1.000000,1.000000,2.000000,0,1

In [297]:
player_stats[(player_stats.fury == 0) & (player_stats.riot == 0) & (player_stats.wg13 == 0)].describe()

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot
count,826.000000,824.000000,826.000000,826.000000,826.000000,826.000000,265.000000,265.000000,265.000000,265.000000,826.000000,826.000000,826.000000,826,826.000000,826.000000,826.000000,826,826
mean,661.348668,22.910194,2.979419,0.527369,2.957627,0.522662,1.569811,0.252561,4.135849,0.673046,5.883777,8.895884,9.351646,0,0.144068,0.033898,1.181598,0,0
std,362.121151,21.889687,3.312172,0.618123,3.685108,0.663803,1.826736,0.291949,4.237776,0.693647,1.130751,4.434445,3.988735,0,0.351371,0.181077,0.663106,0,0
min,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,1.000000,3.000000,0,0.000000,0.000000,0.000000,0,0
25%,343.250000,8.000000,1.000000,0.142857,0.000000,0.000000,0.000000,0.000000,1.000000,0.166667,5.000000,6.000000,4.330000,0,0.000000,0.000000,1.000000,0,0
50%,671.500000,17.000000,2.000000,0.333333,2.000000,0.285714,1.000000,0.166667,3.000000,0.500000,6.000000,9.000000,11.000000,0,0.000000,0.000000,1.000000,0,0
75%,974.750000,28.000000,4.000000,0.714286,4.000000,0.741071,2.000000,0.333333,6.000000,1.000000,7.000000,13.000000,12.710000,0,0.000000,0.000000,2.000000,0,0
max,1253.000000,99.000000,22.000000,4.400000,26.000000,4.250000,9.000000,1.500000,39.000000,6.500000,7.000000,16.000000,15.290000,0,1.000000,1.000000,2.000000,0,0

In [355]:
fury_avg_13 = pd.DataFrame(player_stats[(player_stats.Team == 'FURY') & (player_stats.year <= 2013)].mean())

In [356]:
riot_avg_13 = pd.DataFrame(player_stats[(player_stats.Team == 'RIOT') & (player_stats.year <= 2013)].mean())

In [357]:
# TEAM USA stats may be affected by small roster (more PT and opps for stats) so wg_avg take mean stats from only club teams
wg_avg = pd.DataFrame(player_stats[(player_stats.wg13 == 1) & (player_stats.Team != 'TEAM USA') & (player_stats.year <= 2013)].mean())

In [358]:
showdown_avg = pd.DataFrame(player_stats[(player_stats.Team == 'SHOWDOWN') & (player_stats.year <= 2013)].mean())

In [359]:
heist_avg = pd.DataFrame(player_stats[(player_stats.Team == 'HEIST') & (player_stats.year <= 2013)].mean())

In [360]:
scandal_avg = pd.DataFrame(player_stats[(player_stats.Team == 'SCANDAL') & (player_stats.year <= 2013)].mean())

In [361]:
other_avg = pd.DataFrame(player_stats[(player_stats.fury == 0) & (player_stats.riot == 0) & (player_stats.wg13 == 0) & (player_stats.year <= 2013)].mean())

In [363]:
team_avg = pd.concat({'FURY':fury_avg, 'RIOT': riot_avg, 'WG13':wg_avg, 'SHOWDOWN':showdown_avg, 'HEIST':heist_avg, 'SCANDAL':scandal_avg, 'OTHER':other_avg}, axis=1)

In [364]:
team_avg = team_avg[['WG13', 'FURY', 'RIOT', 'HEIST', 'SHOWDOWN', 'SCANDAL', 'OTHER']]

In [365]:
team_avg

,WG13,FURY,RIOT,HEIST,SHOWDOWN,SCANDAL,OTHER
,0,0,0,0,0,0,0
APG,1.271062,0.543282,0.561126,0.430556,0.508571,0.582857,0.449596
Assist,10.769231,3.612403,2.817308,2.583333,3.560000,4.080000,2.777358
BPG,0.888889,0.371429,0.317460,0.305556,0.320000,0.417143,0.252561
Block,6.111111,2.600000,2.222222,1.833333,2.240000,2.920000,1.569811
GPG,0.770147,0.550388,0.564332,0.423611,0.508571,0.588571,0.455256
Games,8.461538,6.767442,5.365385,6.000000,7.000000,7.000000,6.177358
Goal,6.461538,3.666667,2.836538,2.541667,3.560000,4.120000,2.822642
Number,15.307692,24.990476,22.325000,31.208333,26.600000,27.360000,24.464151
Spirit,6.639231,10.878857,10.825375,4.170000,4.140000,4.360000,3.995509
Standing,2.923077,2.201550,2.278846,12.000000,4.000000,1.000000,8.996226
TPG,1.134921,0.680000,0.656085,0.875000,0.651429,0.554286,0.673046
Team_WUGC16,0.692308,0.201550,0.182692,0.041667,0.040000,0.120000,0.041509
Turn,7.666667,4.760000,4.592593,5.250000,4.560000,3.880000,4.135849
Unnamed: 0,167.923077,505.240310,736.711538,143.500000,393.000000,341.000000,223.958491
fury,0.538462,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
k_cluster,0.538462,1.488372,1.615385,0.958333,1.600000,1.600000,1.169811
riot,0.153846,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
wg13,1.000000,0.124031,0.076923,0.041667,0.040000,0.080000,0.000000
wugc16_tryouts,0.923077,0.503876,0.423077,0.083333,0.080000,0.280000,0.143396
year,2012.692308,NaN,NaN,2013.000000,2013.000000,2013.000000,2013.000000

In [300]:
player_stats[(player_stats.wg13 == 1) & (player_stats.Team != 'TEAM USA')].mean()

Unnamed: 0        581.727273
Number             15.357143
Goal                5.151515
GPG                 0.838745
Assist              8.363636
APG                 1.321789
Block               6.111111
BPG                 0.888889
Turn                7.666667
TPG                 1.134921
Games               6.393939
Standing            2.818182
Spirit             10.244286
wg13                1.000000
wugc16_tryouts      0.969697
Team_WUGC16         0.727273
k_cluster           0.696970
fury                0.484848
riot                0.242424
dtype: float64

In [307]:
wg_avg_compare = pd.concat({'WG_stat':pd.DataFrame(player_stats[player_stats.Team == 'TEAM USA'].mean()), 'Club_stat':pd.DataFrame(player_stats[(player_stats.wg13 == 1) & (player_stats.Team != 'TEAM USA')].mean())}, axis=1)

In [308]:
# players on WG13 team were statistically more productive on their club teams than on WG13
wg_avg_compare

                 Club_stat     WG_stat
                         0           0
Unnamed: 0      581.727273  441.833333
Number           15.357143   12.666667
Goal              5.151515    4.500000
GPG               0.838745    0.750000
Assist            8.363636    2.833333
APG               1.321789    0.472222
Block             6.111111         NaN
BPG               0.888889         NaN
Turn              7.666667         NaN
TPG               1.134921         NaN
Games             6.393939    6.000000
Standing          2.818182    1.000000
Spirit           10.244286         NaN
wg13              1.000000    1.000000
wugc16_tryouts    0.969697    0.833333
Team_WUGC16       0.727273    0.666667
k_cluster         0.696970    1.666667
fury              0.484848    0.000000
riot              0.242424    0.000000

In [324]:
print 'Players had ' + str(5.151515/4.500000) + ' times more goals (Goal) on club teams'
print 'Players had ' + str(.838745/0.750000) + ' times more goals per game (GPG) on club teams'
print 'Players had ' + str(8.363636/2.833333) + ' times more assists (Assist) on club teams'
print 'Players had ' + str(1.321789/0.472222) + ' times more assists per game (APG) on club teams'

Players had 1.14478111111 times more goals (Goal) on club teams
Players had 1.11832666667 times more goals per game (GPG) on club teams
Players had 2.95187187669 times more assists (Assist) on club teams
Players had 2.79908390545 times more assists per game (APG) on club teams

In [403]:
# their stats compared to their teammates?
# get individual averages of WG players from club

individual_stats = {}
for item in player_stats[player_stats.wg13 == 1].Name:
    if item not in individual_stats:
        individual_stats[str(item).replace(' ','')] = player_stats[(player_stats.Name == str(item)) & (player_stats.Team != 'TEAM USA')].mean()
        
# player_stats[(player_stats.Name == 'SARAH GRIFFITH') & (player_stats.Team != 'TEAM USA')].mean()

In [404]:
individual_stats.keys()

['OCTAVIAPAYNE',
 'CREEHOWARD',
 'ALEXSNYDER',
 'GEORGIABOSSCHER',
 'SARAHGRIFFITH',
 'ROHRETITCOMB',
 'SANDYJORGENSEN',
 'CARACROUCH',
 'ANNANAZAROV']

In [405]:
# creat individual_stats dfs

for item in individual_stats:
    item = pd.DataFrame(individual_stats[str(item)])

In [406]:
octavia = pd.DataFrame(individual_stats['OCTAVIAPAYNE'])
cree = pd.DataFrame(individual_stats['CREEHOWARD'])
alex = pd.DataFrame(individual_stats['ALEXSNYDER'])
georgia = pd.DataFrame(individual_stats['GEORGIABOSSCHER'])
sarah = pd.DataFrame(individual_stats['SARAHGRIFFITH'])
rohre = pd.DataFrame(individual_stats['ROHRETITCOMB'])
sandy = pd.DataFrame(individual_stats['SANDYJORGENSEN'])
cara = pd.DataFrame(individual_stats['CARACROUCH'])
anna = pd.DataFrame(individual_stats['ANNANAZAROV'])

In [407]:
indi_avg = pd.concat({'OCTAVIA PAYNE':octavia, 'CREE HOWARD': cree, 'ALEX SNYDER':alex, 'GEORGIA BOSSCHER':georgia, 'SARAH GRIFFITH':sarah, 'ROHRE TITCOMB':rohre, 'SANDY JORGENSEN':sandy, 'CARA CROUCH':cara, 'ANNA NAZAROV':anna}, axis=1)

In [408]:
indi_avg

,ALEX SNYDER,ANNA NAZAROV,CARA CROUCH,CREE HOWARD,GEORGIA BOSSCHER,OCTAVIA PAYNE,ROHRE TITCOMB,SANDY JORGENSEN,SARAH GRIFFITH
,0,0,0,0,0,0,0,0,0
Unnamed: 0,53.500000,69.500000,383.000000,59.500000,71.500000,335.000000,304.00,347.000000,306.000000
Number,4.000000,33.000000,5.000000,13.000000,19.000000,9.000000,4.00,37.000000,6.000000
Goal,2.500000,5.500000,5.000000,10.000000,8.500000,6.000000,0.00,12.000000,8.000000
GPG,0.267857,0.666667,0.714286,0.982143,0.875000,0.857143,0.00,1.714286,1.142857
Assist,21.500000,6.000000,20.000000,3.500000,9.000000,14.000000,0.00,9.000000,17.000000
APG,2.119048,0.619048,2.857143,0.321429,0.916667,2.000000,0.00,1.285714,2.428571
Block,7.000000,7.000000,5.000000,3.000000,6.000000,8.000000,0.00,15.000000,4.000000
BPG,1.000000,1.000000,0.714286,0.428571,1.000000,1.142857,0.00,2.142857,0.571429
Turn,9.000000,7.000000,8.000000,4.000000,15.000000,17.000000,0.00,5.000000,4.000000
TPG,1.285714,1.000000,1.142857,0.571429,2.500000,2.428571,0.00,0.714286,0.571429
Games,9.500000,9.500000,7.000000,9.500000,9.000000,7.000000,7.00,7.000000,7.000000
Standing,2.000000,2.000000,4.000000,2.000000,7.000000,1.000000,3.00,1.000000,3.000000
Spirit,8.070000,8.070000,4.140000,8.070000,8.085000,4.360000,4.43,4.360000,4.430000
wg13,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000
wugc16_tryouts,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000
Team_WUGC16,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.00,0.000000,1.000000
k_cluster,0.000000,1.000000,0.000000,1.000000,0.500000,0.000000,2.00,0.000000,0.000000
fury,1.000000,1.000000,0.000000,1.000000,0.500000,0.000000,0.00,0.000000,0.000000
riot,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00,0.000000,1.000000
year,2012.500000,2012.500000,2013.000000,2012.500000,2012.500000,2013.000000,2013.00,2013.000000,2013.000000

In [409]:
player_stats[(player_stats.Name == 'ROHRE TITCOMB') & (player_stats.year <= 2013)]

,Unnamed: 0,Team,Number,Name,Goal,GPG,Assist,APG,Block,BPG,...,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster,fury,riot,year
250,304,RIOT,4,ROHRE TITCOMB,0,0,0,0,0,0,...,2013 USAU Club Championships,3,4.43,1,1,1,2,0,1,2013

In [226]:
player_stats[player_stats.riot == 1].mean()

Unnamed: 0        736.711538
Number             22.325000
Goal                2.836538
GPG                 0.564332
Assist              2.817308
APG                 0.561126
Block               2.222222
BPG                 0.317460
Turn                4.592593
TPG                 0.656085
Games               5.365385
Standing            2.278846
Spirit             10.825375
wg13                0.076923
wugc16_tryouts      0.423077
Team_WUGC16         0.182692
k_cluster           1.615385
fury                0.000000
riot                1.000000
dtype: float64

In [227]:
player_stats[(player_stats.fury == 0) & (player_stats.riot == 0) & (player_stats.wg13 == 0)].mean()

Unnamed: 0        661.348668
Number             22.910194
Goal                2.979419
GPG                 0.527369
Assist              2.957627
APG                 0.522662
Block               1.569811
BPG                 0.252561
Turn                4.135849
TPG                 0.673046
Games               5.883777
Standing            8.895884
Spirit              9.351646
wg13                0.000000
wugc16_tryouts      0.144068
Team_WUGC16         0.033898
k_cluster           1.181598
fury                0.000000
riot                0.000000
dtype: float64

## KNN

In [97]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [98]:
# assign X and y
feature_cols = ['Goal', 'GPG', 'Assist', 'APG']
X = player_stats[feature_cols]
y = player_stats.wg13

In [101]:
player_stats.tail()

,Unnamed: 0,Team,Number,Name,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16
1069,1276,RIOT,27,JULIA SNYDER,1,0.142857,3,0.428571,NaN,NaN,NaN,NaN,7,2015 USAU Club Championships,2,14,0,0,0
1070,1277,RIOT,34,ANGELICA BOYDEN,5,0.714286,6,0.857143,NaN,NaN,NaN,NaN,7,2015 USAU Club Championships,2,14,0,0,0
1071,1278,RIOT,55,NORA CARR,1,0.142857,2,0.285714,NaN,NaN,NaN,NaN,7,2015 USAU Club Championships,2,14,0,0,0
1072,1279,RIOT,77,JILLIAN GOODREAU,1,0.142857,0,0.000000,NaN,NaN,NaN,NaN,7,2015 USAU Club Championships,2,14,0,0,0
1073,1280,RIOT,81,CHARLIE MERCER,4,0.571429,5,0.714286,NaN,NaN,NaN,NaN,7,2015 USAU Club Championships,2,14,0,0,0

In [102]:
# train the model on the entire dataset
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [103]:
# predict the response values for the observations in X ("test the model")
knn.predict(X)

array([1, 1, 0, ..., 0, 0, 0])

In [104]:
# store the predicted response values
y_pred_class = knn.predict(X)

In [105]:
from sklearn import metrics
print metrics.accuracy_score(y, y_pred_class)

0.977653631285

In [118]:
anew = pd.DataFrame(player_stats[['Name','wg13']])
anew.tail()

                  Name  wg13
1069      JULIA SNYDER     0
1070   ANGELICA BOYDEN     0
1071         NORA CARR     0
1072  JILLIAN GOODREAU     0
1073    CHARLIE MERCER     0

In [119]:
wg13_pred = [int(item) for item in y_pred_class]

In [120]:
anew['wg'] = wg13_pred
# new.shape
# len(wg13_pred)

In [122]:
anew[anew.wg == 1]

                  Name  wg13  wg
0          ALEX SNYDER     1   1
1     GEORGIA BOSSCHER     1   1
3          CREE HOWARD     1   1
15        ANNA NAZAROV     1   1
80         ALEX SNYDER     1   1
97        ANNA NAZAROV     1   1
220    MIRANDA KNOWLES     0   1
252     SARAH GRIFFITH     1   1
280      OCTAVIA PAYNE     1   1
326        CARA CROUCH     1   1
349        ALEX SNYDER     1   1
353     SARAH GRIFFITH     1   1
384      ROHRE TITCOMB     1   1
386     SARAH GRIFFITH     1   1
434        ALEX SNYDER     1   1
472   GEORGIA BOSSCHER     1   1
636      OCTAVIA PAYNE     1   1
646    SANDY JORGENSEN     1   1
705        CREE HOWARD     1   1
706      KELLY JOHNSON     0   1
709      KRISTIE BOWEN     0   1
710    ANGELICA BOYDEN     0   1
711    CALISE CARDENAS     0   1
712    LAKSHMI NARAYAN     0   1
713       MAGGIE RUDEN     0   1
714      ROHRE TITCOMB     1   1
845        ALEX SNYDER     1   1
864       ANNA NAZAROV     1   1
926      OCTAVIA PAYNE     1   1
1042   HAYLEY WAHLROOS     0   1
1053    SARAH GRIFFITH     1   1

## Another KNN

In [181]:
# df without NaN values for Blocks and Turns
clean_stats = player_stats.iloc[:, :19].dropna()

In [200]:
clean_stats

,Unnamed: 0,Team,Number,Name,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16
28,28,BENT,0,BRITTANY KAPLAN,0,0.000000,3,0.500000,2,0.333333,5,0.833333,6,2013 USAU Club Championships,13,4.00,0,0,0
29,29,BENT,1,LEXI ZALK,4,0.666667,1,0.166667,4,0.666667,0,0.000000,6,2013 USAU Club Championships,13,4.00,0,0,0
30,30,BENT,2,KAREN CHALIF,3,0.500000,1,0.166667,0,0.000000,6,1.000000,6,2013 USAU Club Championships,13,4.00,0,0,0
31,31,BENT,3,JUDY JARVIS,3,0.500000,7,1.166667,2,0.333333,11,1.833333,6,2013 USAU Club Championships,13,4.00,0,0,0
32,32,BENT,5,KATHERINE COLE,1,0.166667,1,0.166667,1,0.166667,2,0.333333,6,2013 USAU Club Championships,13,4.00,0,0,0
33,33,BENT,6,ASHLEY DALY MORGAN,19,3.166667,3,0.500000,3,0.500000,3,0.500000,6,2013 USAU Club Championships,13,4.00,0,1,0
34,34,BENT,7,ELIZABETH MIDDLETON,2,0.333333,1,0.166667,2,0.333333,5,0.833333,6,2013 USAU Club Championships,13,4.00,0,0,0
35,35,BENT,8,MARISA WILSON,2,0.333333,0,0.000000,0,0.000000,2,0.333333,6,2013 USAU Club Championships,13,4.00,0,0,0
36,36,BENT,12,REBEKAH SOUDER-RUSSO,6,1.000000,2,0.333333,1,0.166667,10,1.666667,6,2013 USAU Club Championships,13,4.00,0,0,0
37,37,BENT,13,REBECCA TUCKER,5,0.833333,14,2.333333,1,0.166667,16,2.666667,6,2013 USAU Club Championships,13,4.00,0,0,0
38,38,BENT,14,KERRY BEYRER,2,0.333333,2,0.333333,0,0.000000,4,0.666667,6,2013 USAU Club Championships,13,4.00,0,0,0
39,39,BENT,15,DIANA DELEO,4,0.666667,0,0.000000,0,0.000000,1,0.166667,6,2013 USAU Club Championships,13,4.00,0,0,0
40,40,BENT,16,EMILY CHO,0,0.000000,2,0.333333,1,0.166667,2,0.333333,6,2013 USAU Club Championships,13,4.00,0,0,0
41,41,BENT,17,ANGEL LI,0,0.000000,1,0.166667,0,0.000000,1,0.166667,6,2013 USAU Club Championships,13,4.00,0,0,0
42,42,BENT,18,KENDRA FREDERICK,3,0.500000,3,0.500000,4,0.666667,0,0.000000,6,2013 USAU Club Championships,13,4.00,0,0,0
43,43,BENT,19,MEGAN RANDALL,4,0.666667,0,0.000000,2,0.333333,2,0.333333,6,2013 USAU Club Championships,13,4.00,0,1,0
44,44,BENT,21,CARA BROWN,0,0.000000,2,0.333333,1,0.166667,4,0.666667,6,2013 USAU Club Championships,13,4.00,0,0,0
45,45,BENT,22,ANNA MEMBRINO,0,0.000000,7,1.166667,0,0.000000,6,1.000000,6,2013 USAU Club Championships,13,4.00,0,0,0
46,46,BENT,25,EMMA KAHLE,0,0.000000,2,0.333333,0,0.000000,0,0.000000,6,2013 USAU Club Championships,13,4.00,0,0,0
47,47,BENT,27,AKINA YOUNGE,0,0.000000,4,0.666667,2,0.333333,3,0.500000,6,2013 USAU Club Championships,13,4.00,0,0,0
48,48,BENT,41,KATIE TALAY,1,0.166667,0,0.000000,0,0.000000,1,0.166667,6,2013 USAU Club Championships,13,4.00,0,0,0
49,49,BENT,47,ANNE SILVER,1,0.166667,0,0.000000,1,0.166667,2,0.333333,6,2013 USAU Club Championships,13,4.00,0,0,0
50,50,BENT,71,CASSANDRA WONG,0,0.000000,0,0.000000,3,0.500000,4,0.666667,6,2013 USAU Club Championships,13,4.00,0,1,0
51,51,BENT,77,MINERVA MUZQUIZ,0,0.000000,2,0.333333,0,0.000000,4,0.666667,6,2013 USAU Club Championships,13,4.00,0,0,0
52,52,BENT,88,KELLY HYLAND,2,0.333333,7,1.166667,8,1.333333,5,0.833333,6,2013 USAU Club Championships,13,4.00,0,1,0
53,54,BRUTE SQUAD,1,KELLY TIDWELL,7,1.166667,3,0.500000,2,0.333333,8,1.333333,6,2013 USAU Club Championships,6,4.00,0,0,0
54,55,BRUTE SQUAD,2,COURTNEY KIESOW,2,0.333333,1,0.166667,1,0.166667,2,0.333333,6,2013 USAU Club Championships,6,4.00,0,1,0
55,56,BRUTE SQUAD,3,SARA JACOBI,3,0.500000,0,0.000000,3,0.500000,3,0.500000,6,2013 USAU Club Championships,6,4.00,0,0,0
56,57,BRUTE SQUAD,4,BETSY CALKINS,0,0.000000,0,0.000000,0,0.000000,2,0.333333,6,2013 USAU Club Championships,6,4.00,0,0,0
57,58,BRUTE SQUAD,5,BLAKE SPITZ,0,0.000000,0,0.000000,1,0.166667,0,0.000000,6,2013 USAU Club Championships,6,4.00,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,375,SCHWA,28,MEGHAN MILLER,4,0.666667,2,0.333333,4,0.666667,5,0.833333,6,2013 USAU Club Championships,15,4.33,0,0,0
320,376,SCHWA,29,LORA LIEGEL,0,0.000000,0,0.000000,0,0.000000,1,0.166667,6,2013 USAU Club Championships,15,4.33,0,0,0
321,377,SCHWA,33,CATE ROSCOE,0,0.000000,4,0.666667,1,0.166667,7,1.166667,6,2013 USAU Club Championships,15,4.33,0,0,0
322,378,SCHWA,77,JEN SANDERSON,2,0.333333,1,0.166667,3,0.500000,2,0.333333,6,2013 USAU Club Championships,15,4.33,0,0,0
323,379,SCHWA,87,JENICA VILLAMOR,1,0.166667,2,0.333333,0,0.000000,5,0.833333,6,2013 USAU Club Championships,15,4.33,0,0,0
324,381,SHOWDOWN,2,LISA ETCHISON,0,0.000000,0,0.000000,0,0.000000,1,0.142857,7,2013 USAU Club Championships,4,4.14,0,0,0
325,382,SHOWDOWN,3,BECCA SHELTON,2,0.285714,0,0.000000,0,0.000000,1,0.142857,7,2013 USAU Club Championships,4,4.14,0,0,0
326,383,SHOWDOWN,5,CARA CROUCH,5,0.714286,20,2.857143,5,0.714286,8,1.142857,7,2013 USAU Club Championships,4,4.14,1,0,0
327,384,SHOWDOWN,6,SHEILA OGDEN,3,0.428571,0,0.000000,0,0.000000,6,0.857143,7,2013 USAU Club Championships,4,4.14,0,0,0
328,385,SHOWDOWN,7,FRANCES TSUKANO,5,0.714286,0,0.000000,1,0.142857,2,0.285714,7,2013 USAU Club Championships,4,4.14,0,0,0
329,386,SHOWDOWN,8,SHEREEN RABIE,7,1.000000,6,0.857143,3,0.428571,17,2.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
330,387,SHOWDOWN,11,KATEY FORTH,7,1.000000,16,2.285714,5,0.714286,15,2.142857,7,2013 USAU Club Championships,4,4.14,0,1,1
331,388,SHOWDOWN,12,DIANA CHARRIER,5,0.714286,4,0.571429,2,0.285714,4,0.571429,7,2013 USAU Club Championships,4,4.14,0,0,0
332,389,SHOWDOWN,13,SARAH BLYTH,2,0.285714,14,2.000000,8,1.142857,11,1.571429,7,2013 USAU Club Championships,4,4.14,0,0,0
333,390,SHOWDOWN,14,EDITH TENG,0,0.000000,0,0.000000,0,0.000000,3,0.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
334,391,SHOWDOWN,15,MARJO POINDEXTER,2,0.285714,0,0.000000,2,0.285714,1,0.142857,7,2013 USAU Club Championships,4,4.14,0,0,0
335,392,SHOWDOWN,16,SARAH LEVINN,12,1.714286,0,0.000000,2,0.285714,0,0.000000,7,2013 USAU Club Championships,4,4.14,0,1,0
336,393,SHOWDOWN,17,ENESSA JANES,7,1.000000,0,0.000000,5,0.714286,3,0.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
337,394,SHOWDOWN,18,HANNAH MURRAY,1,0.142857,0,0.000000,1,0.142857,1,0.142857,7,2013 USAU Club Championships,4,4.14,0,0,0
338,395,SHOWDOWN,23,LILLY WHITE,2,0.285714,0,0.000000,1,0.142857,2,0.285714,7,2013 USAU Club Championships,4,4.14,0,0,0
339,396,SHOWDOWN,24,HOLLY GREUNKE,1,0.142857,5,0.714286,5,0.714286,5,0.714286,7,2013 USAU Club Championships,4,4.14,0,0,0
340,397,SHOWDOWN,25,TINA WOODINGS,1,0.142857,3,0.428571,4,0.571429,6,0.857143,7,2013 USAU Club Championships,4,4.14,0,0,0
341,398,SHOWDOWN,27,CHRISTINA CONTRERAS,10,1.428571,2,0.285714,1,0.142857,4,0.571429,7,2013 USAU Club Championships,4,4.14,0,0,0
342,399,SHOWDOWN,31,SHELBY KUNI,4,0.571429,3,0.428571,6,0.857143,3,0.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
343,400,SHOWDOWN,32,BEX FORTH,4,0.571429,6,0.857143,4,0.571429,3,0.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
344,401,SHOWDOWN,34,JESS HUYNH,2,0.285714,2,0.285714,0,0.000000,3,0.428571,7,2013 USAU Club Championships,4,4.14,0,0,0
345,402,SHOWDOWN,71,ANNA SCHOTT,1,0.142857,3,0.428571,0,0.000000,0,0.000000,7,2013 USAU Club Championships,4,4.14,0,0,0
346,403,SHOWDOWN,75,AUSTINE LIN,0,0.000000,1,0.142857,1,0.142857,2,0.285714,7,2013 USAU Club Championships,4,4.14,0,0,0
347,404,SHOWDOWN,77,RACHEL MASSEY,3,0.428571,2,0.285714,0,0.000000,4,0.571429,7,2013 USAU Club Championships,4,4.14,0,0,0
348,405,SHOWDOWN,99,JANEL VENZANT,3,0.428571,2,0.285714,0,0.000000,9,1.285714,7,2013 USAU Club Championships,4,4.14,0,0,0

In [195]:
knn2 = KNeighborsClassifier(n_neighbors=10)
knn2

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=10, p=2, weights='uniform')

In [184]:
# assign X and y
feature_cols = ['Block', 'BPG', 'Standing']
X = clean_stats[feature_cols]
y = clean_stats.wg13

In [196]:
# train the model on the entire dataset
knn2.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=10, p=2, weights='uniform')

In [197]:
knn2.predict(X)
y_pred_class = knn2.predict(X)

In [198]:
from sklearn import metrics
print metrics.accuracy_score(y, y_pred_class)

0.971962616822

In [199]:
y_pred_class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [191]:
hmm = pd.DataFrame(clean_stats[['Name','wg13']])
wg13_pred_hmm = [int(item) for item in y_pred_class]
hmm['wg'] = wg13_pred_hmm

In [194]:
hmm[hmm.wg13 ==1]

                 Name  wg13  wg
80        ALEX SNYDER     1   0
89        CREE HOWARD     1   0
97       ANNA NAZAROV     1   0
114  GEORGIA BOSSCHER     1   0
250     ROHRE TITCOMB     1   0
252    SARAH GRIFFITH     1   0
280     OCTAVIA PAYNE     1   0
292   SANDY JORGENSEN     1   0
326       CARA CROUCH     1   0

## KNN train test split

In [172]:
feature_cols = ['Goal', 'GPG', 'Assist', 'APG']
X_train = player_stats[player_stats.wg13 == 1][feature_cols]
y_train = player_stats[player_stats.wg13 == 1].wg13

X_test = player_stats[player_stats.wg13 != 1][feature_cols]
y_test = player_stats[player_stats.wg13 != 1].wg13

In [173]:
print X_train.shape
print y_train.shape
print X_test.shape
print y_test.shape

(39, 4)
(39,)
(1035, 4)
(1035,)

In [174]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=10, p=2, weights='uniform')

In [175]:
y_pred_class = knn.predict(X_test)
print metrics.accuracy_score(y_test, y_pred_class)

0.0

In [177]:
y_pred_class.shape

(1035,)

In [180]:
feature_cols = ['Goal', 'GPG', 'Assist', 'APG']
X = player_stats[feature_cols]
y = player_stats.wg13

# calculate TRAINING ERROR and TESTING ERROR for K=1 through 100
k_range = range(1, 101)
training_error = []
testing_error = []

for k in k_range:

    # instantiate the model with the current K value
    knn = KNeighborsClassifier(n_neighbors=k)

    # calculate training error
    knn.fit(X, y)
    y_pred_class = knn.predict(X)
    training_accuracy = metrics.accuracy_score(y, y_pred_class)
    training_error.append(1 - training_accuracy)
    
    # calculate testing error
    knn.fit(X_train, y_train)
    y_pred_class = knn.predict(X_test)
    testing_accuracy = metrics.accuracy_score(y_test, y_pred_class)
    testing_error.append(1 - testing_accuracy)

ValueError: Expected n_neighbors <= 39. Got 40

In [ ]:
# create a DataFrame of K, training error, and testing error
column_dict = {'K': k_range, 'training error':training_error, 'testing error':testing_error}
df = pd.DataFrame(column_dict).set_index('K').sort_index(ascending=False)
df.head()

## Clustering

In [35]:
# df without Team USA
us_stats = us_female_stats[us_female_stats.Team != 'TEAM USA']

In [36]:
# us_stats.groupby('Team').count()

In [37]:
# us_female_stats.groupby('Team').count()

Cluster using all data

In [203]:
X = clean_stats[['Block', 'BPG', 'Standing']]

In [204]:
# K-means clustering
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3, random_state=1)
km.fit(X)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=3, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=1, tol=0.0001,
    verbose=0)

In [205]:
clean_stats['k_cluster'] = km.labels_
clean_stats[clean_stats.k_cluster == 1].groupby('Team').mean().sort_values(by='k_cluster', ascending=False)

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Team,,,,,,,,,,,,,,,,,
BENT,40.0,23.000000,2.480000,0.413333,2.600000,0.433333,1.520000,0.253333,3.960000,0.660000,6,13,4.00,0.000000,0.160000,0.000000,1
HEIST,143.5,31.208333,2.541667,0.423611,2.583333,0.430556,1.833333,0.305556,5.250000,0.875000,6,12,4.17,0.041667,0.083333,0.041667,1
MOLLY BROWN,168.5,23.541667,3.333333,0.555556,3.291667,0.548611,1.541667,0.256944,4.000000,0.666667,6,11,3.83,0.000000,0.250000,0.083333,1
NIGHTLOCK,219.0,25.640000,2.160000,0.360000,2.160000,0.360000,1.400000,0.233333,5.080000,0.846667,6,9,3.67,0.000000,0.040000,0.000000,1
OZONE,264.5,24.083333,2.916667,0.486111,2.916667,0.486111,1.291667,0.215278,3.208333,0.534722,6,9,3.00,0.000000,0.166667,0.041667,1
PHOENIX,288.5,24.500000,2.954545,0.492424,3.000000,0.500000,1.545455,0.257576,5.000000,0.833333,6,14,4.33,0.000000,0.136364,0.045455,1
SCHWA,367.0,19.040000,1.920000,0.320000,1.960000,0.326667,1.560000,0.260000,4.560000,0.760000,6,15,4.33,0.000000,0.040000,0.000000,1

In [206]:
clean_stats[clean_stats.k_cluster == 2].groupby('Team').mean().sort_values(by='k_cluster', ascending=False)

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Team,,,,,,,,,,,,,,,,,
BRUTE SQUAD,66.500000,19.000000,2.576923,0.429487,2.615385,0.435897,0.884615,0.147436,3.384615,0.564103,6,6,4.00,0.000000,0.269231,0.076923,2
FURY,119.066667,28.600000,3.733333,0.533333,3.066667,0.438095,1.000000,0.142857,4.333333,0.619048,7,2,4.14,0.000000,0.333333,0.066667,2
NEMESIS,194.238095,26.571429,2.238095,0.373016,2.571429,0.428571,0.952381,0.158730,3.333333,0.555556,6,5,4.17,0.000000,0.047619,0.000000,2
RIOT,314.526316,26.684211,2.210526,0.315789,2.473684,0.353383,0.789474,0.112782,3.052632,0.436090,7,3,4.43,0.052632,0.263158,0.052632,2
SCANDAL,341.000000,24.357143,3.000000,0.428571,3.000000,0.428571,0.857143,0.122449,2.214286,0.316327,7,1,4.36,0.000000,0.214286,0.142857,2
SHOWDOWN,393.000000,29.823529,3.411765,0.487395,1.294118,0.184874,0.823529,0.117647,3.529412,0.504202,7,4,4.14,0.000000,0.058824,0.000000,2

In [207]:
clean_stats[clean_stats.k_cluster == 2].groupby('Name').count().sort_values(by='k_cluster', ascending=False).head(24)

,Unnamed: 0,Team,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Name,,,,,,,,,,,,,,,,,,,
ALDEN FLETCHER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ALICIA DANTZKER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARJO POINDEXTER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARISA MEAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARGALIT GOULD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MANISHA DARYANI,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MAGGIE RUDEN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LIZZY SHIEL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LISA PITCAITHLEY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LISA ETCHISON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LINDSEY HACK,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LILLY WHITE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEILA TUNNELL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEAH TSINAJINNIE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN SADLER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN NELSON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN CASEY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN BAECHER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAURA MOORE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAURA BITTERMAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAKSHMI NARAYAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KRISTIN FRANKE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KRISTIE BOWEN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KIRSTEN UNFRIED,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [208]:
clean_stats[clean_stats.k_cluster == 2].groupby('Name').count().sort_values(by='k_cluster', ascending=False)

,Unnamed: 0,Team,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Tournament,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Name,,,,,,,,,,,,,,,,,,,
ALDEN FLETCHER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ALICIA DANTZKER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARJO POINDEXTER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARISA MEAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MARGALIT GOULD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MANISHA DARYANI,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MAGGIE RUDEN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LIZZY SHIEL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LISA PITCAITHLEY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LISA ETCHISON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LINDSEY HACK,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LILLY WHITE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEILA TUNNELL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEAH TSINAJINNIE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN SADLER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN NELSON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN CASEY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAUREN BAECHER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAURA MOORE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAURA BITTERMAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LAKSHMI NARAYAN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KRISTIN FRANKE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KRISTIE BOWEN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KIRSTEN UNFRIED,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KELLY TIDWELL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KELLY BOLT,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KATIE DYER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MIA GREENWALD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MICHAELA FALLON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
MICHELA MEISTER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ALIKA JOHNSTON,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
COURTNEY KIESOW,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DARRAGH CLANCY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
KATE KINGERY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HAILEY ALM,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JULIE MALECEK,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JULIA WEINERT,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JILLIAN GOODREAU,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JESS HUYNH,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JENNY FEY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JANEL VENZANT,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JACQUELINE JARIK,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
JACKIE BOOTH,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HEIDI-MARIE WIGGINS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HANNAH MURRAY,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
HANNAH KREILKAMP,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
GWEN AMBLER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DIANA CHARRIER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
GENEVIEVE LAROCHE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
FRANCES TSUKANO,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
FIONA MCKIBBEN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
EMILY HADEL,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
EMILY BAECHER,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
EMILIA GARCIA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ELLE BURSTEIN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
ELANA SCHWAM,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
EDITH TENG,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DORY ZIPERSTEIN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
DOMINIQUE FONTENETTE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
VICKY NEGUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

Cluster without Team USA

In [210]:
noUSA = player_stats[player_stats.Team != 'TEAM USA']
X = noUSA[['Goal', 'GPG', 'Assist', 'APG', 'Standing']]

In [211]:
# K-means clustering
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3, random_state=1)
km.fit(X)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=3, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=1, tol=0.0001,
    verbose=0)

In [215]:
noUSA['k_cluster'] = km.labels_
noUSA[(noUSA.k_cluster == 2) & (noUSA.wugc16_tryouts >0)].groupby('Name').mean().sort_values(by='k_cluster', ascending=False).head(35)

/Users/octaviapayne/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Name,,,,,,,,,,,,,,,,,
ALEX SNYDER,371.666667,4.000000,2.333333,0.289683,18.000000,2.023810,7,1.000000,9,1.285714,8.333333,2.333333,9.913333,1,1,1,2
MANISHA DARYANI,71.500000,71.000000,7.000000,0.761905,7.000000,0.851190,1,0.142857,9,1.285714,9.500000,2.000000,8.070000,0,1,0,2
KATHERINE WOOTEN,866.500000,24.000000,3.500000,0.585714,19.500000,3.328571,NaN,NaN,NaN,NaN,6.000000,7.000000,10.785000,0,1,0,2
KATHLEEN RATCLIFF,1215.000000,13.000000,1.000000,0.142857,15.000000,2.142857,NaN,NaN,NaN,NaN,7.000000,6.000000,11.640000,0,1,0,2
KELLY JOHNSON,725.000000,11.000000,3.000000,0.452381,8.000000,1.238095,6,1.000000,10,1.666667,6.500000,3.500000,9.085000,0,1,0,2
LAKSHMI NARAYAN,518.500000,66.000000,6.500000,0.875000,10.500000,1.208333,NaN,NaN,NaN,NaN,9.000000,2.500000,12.800000,0,1,0,2
LAURA BITTERMAN,1202.000000,33.000000,11.000000,1.571429,4.000000,0.571429,NaN,NaN,NaN,NaN,7.000000,1.000000,11.000000,0,1,0,2
LEILA TUNNELL,664.666667,18.000000,2.000000,0.317460,11.666667,1.817460,0,0.000000,8,1.333333,6.333333,3.333333,9.466667,0,1,1,2
LIEN HOFFMANN,700.000000,8.666667,9.666667,1.547619,6.333333,1.015873,8,1.333333,9,1.500000,6.333333,3.000000,9.523333,0,1,1,2
LISA PITCAITHLEY,343.000000,26.000000,7.500000,1.071429,6.500000,0.928571,2,0.285714,2,0.285714,7.000000,2.000000,8.785000,0,1,0,2
LORYN KANEMARU,912.000000,3.000000,4.000000,0.571429,13.000000,1.857143,NaN,NaN,NaN,NaN,7.000000,7.000000,10.430000,0,1,0,2
MAGGIE RUDEN,68.000000,44.000000,9.500000,1.000000,3.500000,0.440476,2,0.285714,5,0.714286,9.500000,2.000000,8.070000,0,1,1,2
MEG HARRIS,1097.000000,27.000000,10.000000,1.428571,7.000000,1.000000,NaN,NaN,NaN,NaN,7.000000,9.000000,10.710000,0,1,0,2
ALEXI ZALK,960.000000,1.000000,15.000000,2.142857,7.000000,1.000000,NaN,NaN,NaN,NaN,7.000000,14.000000,7.430000,0,1,0,2
MIRA WALKER,645.000000,44.000000,11.000000,2.200000,6.000000,1.200000,NaN,NaN,NaN,NaN,5.000000,5.000000,10.860000,0,1,1,2
NESS FAJARDO,8.000000,27.000000,0.000000,0.000000,15.000000,1.250000,NaN,NaN,NaN,NaN,12.000000,2.000000,12.000000,0,1,0,2
OCTAVIA PAYNE,739.333333,9.000000,3.666667,0.531746,15.000000,2.206349,8,1.142857,17,2.428571,6.666667,1.666667,9.466667,1,1,1,2
ROBYN WISEMAN,586.333333,10.666667,4.333333,0.884921,19.333333,3.527778,9,1.500000,39,6.500000,5.666667,10.666667,9.960000,0,1,0,2
ROHRE TITCOMB,879.000000,4.000000,1.500000,0.226190,10.500000,1.654762,NaN,NaN,NaN,NaN,6.500000,2.500000,14.085000,1,1,1,2
SALLY LAMBERT,666.000000,28.000000,10.000000,2.000000,3.000000,0.600000,NaN,NaN,NaN,NaN,5.000000,9.000000,13.710000,0,1,0,2
SANDY JORGENSEN,785.333333,37.000000,13.666667,1.952381,7.000000,1.000000,15,2.142857,5,0.714286,7.000000,2.666667,9.570000,1,1,0,2
SARAH GRIFFITH,689.333333,6.000000,10.333333,1.555556,9.666667,1.436508,4,0.571429,4,0.571429,6.666667,2.666667,10.866667,1,1,1,2
SARAH ITOH,1207.000000,4.000000,21.000000,3.000000,7.000000,1.000000,NaN,NaN,NaN,NaN,7.000000,6.000000,11.640000,0,1,0,2
SARAH LEVINN,535.000000,16.000000,13.000000,2.600000,1.000000,0.200000,NaN,NaN,NaN,NaN,5.000000,6.000000,11.170000,0,1,0,2
KATEY FORTH,621.333333,11.000000,7.333333,1.180952,12.000000,1.904762,5,0.714286,15,2.142857,6.333333,8.333333,7.816667,0,1,1,2
KAMI GROOM,696.666667,4.333333,11.000000,1.738095,8.000000,1.238095,6,1.000000,4,0.666667,6.333333,3.000000,9.523333,0,1,1,2
KAELA JORGENSON,220.333333,5.666667,6.666667,0.714286,8.333333,0.992063,6,0.857143,6,0.857143,8.666667,2.000000,9.856667,0,1,1,2
JULIA SHERWOOD,68.000000,18.000000,2.000000,0.196429,9.000000,1.017857,4,0.571429,6,0.857143,9.500000,2.000000,8.070000,0,1,0,2
ALYSSA WEATHERFORD,515.000000,25.000000,3.000000,0.500000,9.000000,1.500000,NaN,NaN,NaN,NaN,6.000000,3.000000,14.170000,0,1,0,2
AMBER SINICROPE,624.500000,10.000000,4.000000,0.619048,8.500000,1.321429,2,0.333333,10,1.666667,6.500000,3.500000,7.500000,0,1,1,2
ANNA NAZAROV,536.333333,33.000000,3.000000,0.357143,7.666667,1.000000,NaN,NaN,NaN,NaN,8.333333,2.333333,13.010000,1,1,1,2
ASHLEY DALY MORGAN,33.000000,6.000000,19.000000,3.166667,3.000000,0.500000,3,0.500000,3,0.500000,6.000000,13.000000,4.000000,0,1,0,2
BECKY MALINOWSKI,661.666667,13.000000,11.666667,1.865079,7.666667,1.238095,3,0.500000,4,0.666667,6.333333,3.333333,9.466667,0,1,0,2
BRIANA CAHN,537.000000,20.000000,8.666667,1.714286,6.666667,1.186508,6,1.000000,10,1.666667,5.666667,7.666667,9.270000,0,1,0,2
CALISE CARDENAS,405.000000,7.000000,12.000000,1.821429,3.500000,0.547619,5,0.714286,3,0.428571,6.500000,3.000000,9.300000,0,1,1,2

In [216]:
# clean = clean_stats[clean_stats.Team != 'TEAM USA']
X = clean_stats[['Goal', 'GPG', 'Assist', 'APG', 'Standing', 'Block', 'BPG']]

In [217]:
# K-means clustering
from sklearn.cluster import KMeans
km = KMeans(n_clusters=3, random_state=1)
km.fit(X)

KMeans(copy_x=True, init='k-means++', max_iter=300, n_clusters=3, n_init=10,
    n_jobs=1, precompute_distances='auto', random_state=1, tol=0.0001,
    verbose=0)

In [219]:
clean_stats['k_cluster'] = km.labels_
clean_stats[(clean_stats.k_cluster == 1) & (clean_stats.wugc16_tryouts >0)].groupby('Name').mean().sort_values(by='k_cluster', ascending=False).head(35)

,Unnamed: 0,Number,Goal,GPG,Assist,APG,Block,BPG,Turn,TPG,Games,Standing,Spirit,wg13,wugc16_tryouts,Team_WUGC16,k_cluster
Name,,,,,,,,,,,,,,,,,
ALEX SNYDER,107,4,2,0.285714,11,1.571429,7,1.000000,9,1.285714,7,2,4.14,1,1,1,1
KAMI GROOM,186,5,12,2.000000,8,1.333333,6,1.000000,4,0.666667,6,5,4.17,0,1,1,1
SARAH GRIFFITH,306,6,8,1.142857,17,2.428571,4,0.571429,4,0.571429,7,3,4.43,1,1,1,1
SANDY JORGENSEN,347,37,12,1.714286,9,1.285714,15,2.142857,5,0.714286,7,1,4.36,1,1,0,1
ROBYN WISEMAN,139,14,2,0.333333,20,3.333333,9,1.500000,39,6.500000,6,12,4.17,0,1,0,1
OCTAVIA PAYNE,335,9,6,0.857143,14,2.000000,8,1.142857,17,2.428571,7,1,4.36,1,1,1,1
MANISHA DARYANI,129,71,6,0.857143,9,1.285714,1,0.142857,9,1.285714,7,2,4.14,0,1,0,1
LIEN HOFFMANN,184,3,15,2.500000,9,1.500000,8,1.333333,9,1.500000,6,5,4.17,0,1,1,1
LEILA TUNNELL,67,18,2,0.333333,9,1.500000,0,0.000000,8,1.333333,6,6,4.00,0,1,1,1
KELLY JOHNSON,195,21,2,0.333333,8,1.333333,6,1.000000,10,1.666667,6,5,4.17,0,1,0,1
KATEY FORTH,387,11,7,1.000000,16,2.285714,5,0.714286,15,2.142857,7,4,4.14,0,1,1,1
KAELA JORGENSON,108,5,4,0.571429,7,1.000000,6,0.857143,6,0.857143,7,2,4.14,0,1,1,1
AMBER SINICROPE,62,10,4,0.666667,9,1.500000,2,0.333333,10,1.666667,6,6,4.00,0,1,1,1
JULIA SHERWOOD,120,18,1,0.142857,9,1.285714,4,0.571429,6,0.857143,7,2,4.14,0,1,0,1
JESSI JONES,281,5,0,0.000000,13,2.166667,4,0.666667,12,2.000000,6,14,4.33,0,1,0,1
HANA KAWAI,314,14,13,1.857143,6,0.857143,9,1.285714,16,2.285714,7,3,4.43,0,1,1,1
DENA SLATTERY,163,11,6,1.000000,14,2.333333,4,0.666667,8,1.333333,6,11,3.83,0,1,1,1
CLAIRE CHASTAIN,298,52,1,0.166667,15,2.500000,5,0.833333,19,3.166667,6,14,4.33,0,1,1,1
CALISE CARDENAS,307,7,15,2.142857,3,0.428571,5,0.714286,3,0.428571,7,3,4.43,0,1,1,1
BRIANA CAHN,220,20,6,1.000000,7,1.166667,6,1.000000,10,1.666667,6,9,3.67,0,1,0,1
BECKY MALINOWSKI,65,13,15,2.500000,9,1.500000,3,0.500000,4,0.666667,6,6,4.00,0,1,0,1
ASHLEY DALY MORGAN,33,6,19,3.166667,3,0.500000,3,0.500000,3,0.500000,6,13,4.00,0,1,0,1
SHELLIE COHEN,280,2,7,1.166667,8,1.333333,5,0.833333,16,2.666667,6,14,4.33,0,1,0,1